swagger: '2.0'

host: localhost:8080
basePath: /

info:
  version: 1.0.0
  title: Central de Erros API
  description: Store and retrieve application logs from other applications
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'

components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /logs/environment/{environment}:
    get:
      security:
        - bearerAuth: []
      summary: Get logs by environment
      description: Get all logs of an environment that is passed in the url parameter
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            required: true
        - in: path
          name: environment
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Show all logs
          schema:
            type: array
            items:
              $ref: '#/definitions/Log'
        200_:
          description: Returns a message stating that there are no logs to show for this user
          schema:
            type: object
            properties:
              message:
                type: string
                example: There are no logs
        500:
          description: Returns a message stating that an error has occurred on the server
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal server error

  /logs/restore/all:
    post:
      security:
        - bearerAuth: []
      summary: Restore all logs
      description: Restore all logs created by the user
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            required: true
      responses:
        200:
          description: Returns a succesfull message when all logs from user are restored
          schema:
            type: object
            properties:
              message:
                type: string
                example: All logs restored successfully
        200_:
          description: Returns a message stating that there are no logs to restore for this user
          schema:
            type: object
            properties:
              message:
                type: string
                example: There are no logs
        500:
          description: Returns a message stating that an error has occurred on the server
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal server error

definitions:
  User:
    type: object
    properties:
      name:
        type: string
        example: João da Silva
      email:
        type: string
        example: joao@email.com.br
      password:
        type: string
        format: password
        example: "123456"
    required:
      - name
      - email
      - password
  
  Log:
    type: object
    properties:
      level:
        type: string
        enum: [FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL, OFF]
        example: WARN
      description:
        type: string
        example: Application restarted
      senderApplication:
        type: string
        example: Server load monitor
      sendDate:
        type: string
      environment:
        type: string
        enum: [production, homologation]
        example: homologation
    required: 
      - level
      - description
      - senderApplication
      - sendDate
      - environment
      - userId
